name: Vim Build

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: false
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: windows-latest

    strategy:
      matrix:
        include: [
          { msystem: ucrt64, toolchain: ucrt-x86_64 }
          #,
          #{ msystem: mingw64, toolchain: x86_64 },
          #{ msystem: mingw32, toolchain: i686 }
          ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.toolchain }}-toolchain base-devel binutils git
          pacboy: >-
            aria2:p
            ca-certificates
          update: true
          path-type: inherit

      - name: Set vim build tag
        #if: ${{ "${{github.event.inputs.IMG_URL}}" }}
        if: github.event.inputs.IMG_URL != ''
        shell: msys2 {0}
        run:
          echo "vimTag=${{ github.event.inputs.IMG_URL }}" >> $GITHUB_ENV

      - name: Install scoop tools
        shell: pwsh
        run: .\tools\scoop_vim_install.ps1
        
      - name: Build vim
        shell: msys2 {0}
        run: |
          bash -x tools/vim-build.sh && ls tools/vim/
        env:
          MINGW_ARCH: ${{ matrix.msystem }}
          PKGEXT: ".pkg.tar.xz"
        #shell: cmd
        #run: set

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tools/vim/gvim_*_x86_64.zip
            tools/vim/mingw-w64-ucrt-x86_64-vim*.pkg.tar.xz
      #      ./DeviceTree.zip
      #    name: TWRP_Device_Tree-${{ github.run_id }}
          name: ${{env.tagName}}
      #    tag_name: ${{ github.run_id }}
          tag_name: ${{env.tagName}}
      #    body: DeviceTree for twrp
          body_path: gitlog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
