name: Vim Build

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: false
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: windows-latest

    strategy:
      matrix:
        include: [
          { msystem: ucrt64, toolchain: ucrt-x86_64 }
          #,
          #{ msystem: mingw64, toolchain: x86_64 },
          #{ msystem: mingw32, toolchain: i686 }
          ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-${{ matrix.toolchain }}-toolchain base-devel binutils
          update: true

      - name: Build vim
        run: set

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./DeviceTree.zip
          name: TWRP_Device_Tree-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: DeviceTree for twrp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
